backend:
  name: git-gateway # set to 'proxy' for local development
  proxy_url: http://localhost:8081/api/v1 # enable for local development
  branch: master
local_backend: true
publish_mode: editorial_workflow
media_folder: 'src/media'
public_folder: ''
site_url: https://learn.maproulette.org
display_url: https://learn.maproulette.org
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: Page
    editor:
      preview: false
    files:
      - name: 'home'
        label: 'Home'
        delete: false
        file: 'src/index.md'
        slug: '{{slug}}'
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'home',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Headline', name: 'headline', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: documentation
    label: Documentation
    label_singular: Document
    editor:
      preview: false
    sortable_fields: ['title', 'eleventyNavigation.order']
    folder: 'src/documentation'
    slug: '{{title}}'
    preview_path: 'documentation/{{slug}}'
    extension: md
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'base' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'hidden',
          default: 'documentation',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - label: 'Navigation'
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'key', widget: 'string' }
          - {
              label: 'Parent',
              name: 'parent',
              widget: 'relation',
              collection: 'documentation',
              search_fields: ['title', 'description'],
              value_field: '{{eleventyNavigation.key}}',
              display_fields: ['{{eleventyNavigation.key}}'],
              required: false,
            }
          - { label: 'URL', name: 'url', widget: 'text', required: false }
          - {
              label: 'Order',
              name: 'order',
              widget: 'number',
              value_type: 'float',
              step: .25,
              default: 0,
            }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'boolean',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  - name: screencasts
    label: Screencasts
    label_singular: Screencast
    editor:
      preview: false
    sortable_fields: ['title', 'eleventyNavigation.order']
    folder: 'src/screencasts'
    slug: '{{title}}'
    preview_path: 'screencasts/{{slug}}'
    extension: md
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'base' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'hidden',
          default: 'screencasts',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'Navigation'
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - {
              label: 'Title',
              name: 'key',
              widget: 'string',
              default: '{title}',
            }
          - {
              label: 'Parent',
              name: 'parent',
              widget: 'relation',
              collection: 'screencasts',
              search_fields: ['title', 'description'],
              value_field: '{{eleventyNavigation.key}}',
              display_fields: ['{{eleventyNavigation.key}}'],
              required: false,
            }
          - { label: 'URL', name: 'url', widget: 'text', required: false }
          - {
              label: 'Order',
              name: 'order',
              widget: 'number',
              value_type: 'int',
              step: .25,
              default: 0,
            }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'boolean',
          required: false,
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
